[package]
name = "wkw_save"
version = "0.1.0"
authors = ["Alessandro Motta <alessandro.motta@brain.mpg.de>"]
build = "build.rs"

[dependencies.wkwrap]
path = "../../../rust"

[dependencies.wkw_mex]
path = "../wkw_mex"

[lib]
name = "wkw_save"
crate-type = ["dylib"]
