[package]
name = "wkw"
version = "0.1.0"
authors = ["Alessandro Motta <alessandro.motta@brain.mpg.de>"]

[dependencies]
lazy_static = "0.2"

[dependencies.wkwrap]
path = "../rust"

[lib]
crate-type = ["cdylib"]
