[package]
name = "wkwrap"
version = "1.0.0"
authors = ["Alessandro Motta <alessandro.motta@brain.mpg.de>"]

[dependencies]
walkdir = "1"
libc = "0.2.24"

[lib]
name = "wkwrap"
path = "src/lib.rs"

[[bin]]
name = "wkw"
path = "src/main.rs"
