[package]
name = "wkw_init"
version = "1.0.0"
authors = ["Alessandro Motta <alessandro.motta@brain.mpg.de>"]
build = "build.rs"

[dependencies.wkwrap]
path = "../../../rust"

[dependencies.wkw_mex]
path = "../wkw_mex"

[profile.release]
lto = true

[lib]
name = "wkw_init"
crate-type = ["cdylib"]
